### ISSUE TITLE
Pre-request script to generate token

### ISSUE THREAD

**Issue by gavinr** [esri-es/ArcGIS-REST-API#4]
I would like the ability to, instead of setting a `token` environmental variable, to instead be able to set my `client_id` and `client_secret` and have postman generate a token for me each time the request runs.

Code for this workflow might look something like:

```
var cid = pm.environment.get("clientId");
var cs = pm.environment.get("clientSecret");

const echoPostRequest = {
  url: 'https://www.arcgis.com/sharing/rest/oauth2/token',
  method: 'POST',
  body: {
      mode: "urlencoded",
      urlencoded: "client_id=" + cid + "&client_secret=" + cs + "&grant_type=client_credentials&f=json"
  }
};

pm.sendRequest(echoPostRequest, function (err, response) {
    if (err) { console.log(err); }
    if(response.json().access_token) {
        pm.environment.set("token", response.json().access_token);
    }
});
```

**Comment by hhkaos** [comment]
I've tested it and made a minor change:

```js
pm.sendRequest(echoPostRequest, function (err, response) {
    var res = response.json();
    if (res.error) { console.log(res.error.error_description); }
    if(res.access_token) {
        pm.environment.set("token", res.access_token);
    }
});
```

:dancer:

**Comment by gavinr** [comment]
@hhkaos is this supposed to be in the pre-reqeust script for all requests? After importing into Postman I am not seeing this in any of the endpoints.

**Comment by hhkaos** [comment]
Nope, I just added to one, but now I have just added to all of them that needed it.

Cheers!
P.S: I'm still not sure how some of the URLs are constructed (differences between Enterprise an ArcGIS Online). Would you think that we could involve at least one person from the Enterprise team to speed things up?
