### ISSUE TITLE
Offline Packaging

### ISSUE THREAD

**Issue by MuhammadYasirAlikhan** [esri-es/ArcGIS-REST-API#6]
I m new to rest api and I want to "create map area" following this link
"https://developers.arcgis.com/rest/packaging/api-reference/create-map-area.htm".
However, when I try to use example request, I got the error response as
"Error: Services Directory has been disabled."
Anyone know the issue or mistake on my side?

**Comment by hhkaos** [comment]
sorry @MuhammadYasirAlikhan I couldn't check earlier. I get the same error, [I have just asked on GeoNet](https://community.esri.com/message/756557-create-map-area-using-packagingarcgiscom). Let's see if someone can help us there.

Cheers!

**Comment by hhkaos** [comment]
Hi @MuhammadYasirAlikhan we have already solved the issue as you can read here: https://community.esri.com/thread/211069-create-map-area-using-packagingarcgiscom

Cheers!

**Comment by MuhammadYasirAlikhan** [comment]
Thank you, sir, for your response and sorry I forget to add that I already find the solution to this problem. But now I face another issue for I had asked on the same forum.
https://community.esri.com/message/756213-error-in-executing-agol-rest-api-packaging-service
